### ISSUE TITLE
My MIDI keyboard does not show up in patchage

### ISSUE THREAD

**Issue by Ploppz** [jackaudio/jack2#117]
It did before, and the red connections (JACK MIDI) showed there were quite different than now: http://a.pomf.se/jtvtjv.png (Current).

If I try to connect `alsa_midi` to `events-in` on any of the two VSTs, playing the midi keyboard still has no effect.

I'm using `qjackctl`, and just some days ago, my midi keyboard worked with just the same settings.

In `lsusb`, my midi keyboard is listed as `Bus 009 Device 004: ID 258f:0b01` (it is given no further name). It is Xkey whatsoever.

Is there any more information you need in order to help me?

Thanks.

**Comment by mseeber** [comment]
In the qjackctl settings, which kind of MIDI driver do you have selected? (bottom right section of the window)

You can try `raw` and `seq` and see, if you can get different results.

**Comment by Ploppz** [comment]
I had a similar problem earlier and picking `seq` then did it for me, and that's what the options are set to atm. `raw` did not add any red connectors at all, and `none` did not add any connectors at all.

**Comment by mseeber** [comment]
What you could also try is to us `a2jmidid`. Other that that, it would be interesting to know, what changed from the time, when it was working.
Did you update your System or jack?

**Comment by Ploppz** [comment]
I did update my system 15th of April, but I'm pretty sure it worked after that.
Trying `a2jmidid`, I ran it and re-ran patchage, carla and qjackctl. I'm unsure what I should connect in patchage but this seemed like the reasonable and it does not work:

![img](http://a.pomf.se/rjzouq.png)

These are the other connections available:

![img](http://a.pomf.se/eptyic.png)

**Comment by mseeber** [comment]
Forget the Midi Through Ports, they do not represent your midi device. (They never did for me)

Anyway, The red ones are JACK Midi ports, the purple ones are alsa midi ports. These can not be connected to each other.

1.
One thing you can do, is to run a2jmidid with the "-e" flag, so that also hardware alsa midi ports are exposed as jack midi ports.

2.
Alternatively, running jack manualy from the commandline should also give you jack midi ports, but without pretty names

    /usr/bin/jackd -r -dalsa -Phw:PCH -r48000 -p1024 -n2 -X seq

or

    /usr/bin/jackd -r -dalsa -Phw:PCH -r48000 -p1024 -n2 -X raw

These ports will be named like `midi_playback_1` and show up in the box of the "system." client

This works for me, but if your midi keyboard has no driver support, the ports will not show up anyway.

What distribution and what Kernel version are you using?

**Comment by Ploppz** [comment]
The `-e` flag of a2jmidid does not seem to change anything.

`$ /usr/bin/jackd -r -dalsa -Phw:PCH -r48000 -p1024 -n2 -X seq`:
```
jackd 0.124.1
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details

could not open driver .so '/usr/lib/jack/jack_firewire.so': libffado.so.2: cannot open shared object file: No such file or directory

JACK compiled with System V SHM support.
loading driver ..
apparent rate = 48000
creating alsa driver ... hw:PCH|-|1024|2|48000|0|0|nomon|swmeter|-|32bit
control open "hw:PCH" (No such device)
ALSA lib pcm_hw.c:1693:(_snd_pcm_hw_open) Invalid value for card
ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
cannot load driver module alsa
```
similar output for `raw`

I'm using Pulseaudio btw, if that matters.

**Comment by mseeber** [comment]
ok, afew things can be learnt from that output:

    jackd 0.124.1

so you are using jack1 and not jack2

    $ /usr/bin/jackd -r -dalsa -Phw:PCH -r48000 -p1024 -n2 -X seq

`-d alsa` specifies which backend to use
`-Phw:PCH` specifies which interface to use for audio playback, this is on your system probably not "PCH" (see the contents of /proc/asound/cards)

>I'm using Pulseaudio btw, if that matters.

There can be problems with audio in that case, but i don't know if this causes problems for midi.

For the initial problem:
I guess your Midi Keyboard is just not detected correctly. Does anyone else have an idea?

**Comment by Ploppz** [comment]
Thanks. I updated to jack2. (version is now 1.9.10 is that correct?), and found the right playback device, so the command now works. This is how it looks in patchage:

![img](http://a.pomf.se/crdoto.png)

However, the MIDI keyboard still does not affect the VST.

**Comment by nedko** [comment]
Check if you receive midi events from "midi_capture_1" port and whether they are on correct midi channel.
I don't see VST, only ZynAddSubFX jack client. How MIDI keyboard is supposed to affect a VST?

**Comment by Ploppz** [comment]
ZynAddSubFX is a VST. How do I check if I receive midi events?

**Comment by nedko** [comment]
Probably the simplest is to use the jack_midi_dump command-line tool. Run it with -h parameter to get help text.

**Comment by Ploppz** [comment]
Running it with no flags (also tried the two flags), gave no output when I played the midi keyboard, or plugged it out and in.

**Comment by nedko** [comment]
Make sure that the MIDI ports are connected. If you still don't see the MIDI events, try at ALSA level, with aseqdump tool.

**Comment by Ploppz** [comment]
Ah, it somehow works today, and I'm not sure what I've done different. Maybe I did not connect things right last time. And it also works if I just run `qjackctl` instead of that command \o/

Thanks!

**Comment by Ploppz** [comment]
Hi, I just want to say that I have this issue now again and I haven't found any sustaining solution. Thanks.

**Comment by lilrc** [comment]
Maybe the kernel driver is not always loaded? Which distro do you run? Have you tried looking at `lsmod` when it works and when it does not?

**Comment by JJones780** [comment]
Hi Same issue here... QJackCtrl was able to see them though... so I guess it's an issue with Patchage?
Details:
I just installed Patchage, ZynAddSubFX and Qtractor for the first time.  I was able to see and connect ZynAddSubFX ALSA midi ports and now an hour later they aren't appearing.  I had done a killall jackd in there as well as reloading apps and installing the PulseToJack mapper and running that in order to get sound from my browser without having to kill jackd again.
 I installed QJackCtrl and was able to see the Zyn- midi ports and connect them ... but they still don't show up on Patchage.

**Comment by 7890** [comment]
This issue can be a mixture of several other issues not limited to JACK. It seems that sometimes it worked for you - it shows that it can work and is possibly a configuration or setup issue.

If you think it's an issue of JACK: please describe the issue using as few 3rd party tools as possible.
Also add exact version information of involved 3rd party programs, since they can change behavior over time. Consider filing issues or get support at the home of the corresponding programs.

I will close this issue now. Thanks for caring about JACK!
