### ISSUE TITLE
FreeBSD real-time scheduling?

### ISSUE THREAD

**Issue by moritzbuhl** [jackaudio/jack2#129]
I don't know if I am right here. I installed the audio/jack port ([here](https://www.freshports.org/audio/jack/)). And I don't know how to start jack with real-time scheduling. Can I even do that as normal user?

```
[pasta@x230][pts/2]~: jackd -doss
jackd 0.124.1
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details

JACK compiled with System V SHM support.
cannot use real-time scheduling (FIFO at priority 10) [for thread 29385728, from thread 29385728] (1: Operation not permitted)
cannot create engine

```

If I run jackd as root the programs can't connect to the daemon.

**Comment by mseeber** [comment]
Let's divide this into smaller bits:

* Starting jack with realtime priority as normal user does not work for you, right?
* Does starting jack with realtime priority work for you as root (it sounds as if you tried that)?

If starting jack with realtime priority as root work, you just have to find out how to give your user the permission to use realtime scheduling. I can not help you with that, since i am not that familiar with BSD.

**Comment by GorgonzolaPasta** [comment]
As root works. I'll ask local BSD-Guru and report.

**Comment by 7890** [comment]
It's expected behaviour that when jackd was started as root, normal users can't connect to it.
If you can't start jackd as non-root user with rt prio, the user isn't allowed to use rt and/or lock-down memory. This is a setting that needs to be figured out on FreeBSD. There is nothing jackd can do to fix this. On ubuntu systems, users can get permission by adding a file in /etc/security/limits.d/ that contains roughly these lines:
```
@audio   -  rtprio     95
@audio   -  memlock    unlimited
```
where 'audio' is a group name. Every user in this group can now start jackd with rt prio.
