### ISSUE TITLE
Please do a release.

### ISSUE THREAD

**Issue by magnetophon** [jackaudio/jack2#220]
It's been 2 years since the last release.
Any particular reason for that?

**Comment by magnetophon** [comment]
Any news on this?

**Comment by xjjx** [comment]
+ for fix 32 clients - issue #183

**Comment by magnetophon** [comment]
@sletz It would be really nice if distros could use a new stable version. Would that be possible?

**Comment by magnetophon** [comment]
I'm sorry to keep repeating myself here, but could I get a reaction from the devs?

**Comment by magnetophon** [comment]
@falkTX Many thanks for https://github.com/jackaudio/jack2/releases/tag/v1.9.11-RC1 !!
The people at my distro are a bit worried about it being a pre-release, so don't want to include it in the distro, which was my main goal when asking for this release.
Any idea when a proper release will be made?

**Comment by falkTX** [comment]
the reason for the RC is because we're missing windows and mac binaries.
I want to try to have them sorted out first. If it takes too long, a release will be made without them.

I don't see any changed needed for Linux right now. There's a few pending PRs, but it's for odd uses of jack.
This tag is safe to use in normal distro builds. I've been using the git version of jack2 in kxstudio for several months now.
