### ISSUE TITLE
Jack plays 44 kHz as 48 kHz without resampling, leaving gaps and making pitch higher

### ISSUE THREAD

**Issue by Redsandro** [jackaudio/jack2#334]
No matter what sample rate I set in `qjackctl`, the sample rate in `jack` will always be 48000 Hz. I tried manually killing `jackd` and `jackdbus` in between runs just to be sure.

As a consequence, 44 KHz audio from an ASIO USB device (Vox ToneLab ST) will be played through the sound card in 48 KHz snippets with small pauses between each buffer.

The configured sampling rate is displayed on the `qjackctl` window. (Don't mind the weird scale of things - `qjackctl` seems incompatible with modern display resolutions.)
![image](https://user-images.githubusercontent.com/1702193/37651727-6b07488c-2c39-11e8-9802-dbd7709c434e.png)

In messages you can see this setting is ignored:

> Starting jack server...
> JACK server starting in realtime mode with priority 10
> self-connect-mode is "Don't restrict self connect requests"
> Acquired audio card Audio1
> Acquired audio card Audio0
> creating alsa driver ... hw:PCH,0|hw:ToneLabST,0|128|3|__44100__|0|0|nomon|swmeter|-|16bit
> configuring for __44100Hz__, period = 128 frames (2.9 ms), buffer = 3 periods
> ALSA: final selected sample format for capture: 16bit little-endian
> ALSA: use 3 periods for capture
> ALSA: final selected sample format for playback: 16bit little-endian
> ALSA: use 3 periods for playback
> __ERROR: playback and capture sample rates do not match (48000 vs. 44100)__

I have googled for hours trying to get this to work, but similar reports seem to be scarce and very outdated. [Here is a bugreport](206787) I found that seems related. The response (from 2006!) was that some sound cards can only do one specific sample rate, so jack will run with it even if specified otherwise.

~~First, I hardly think this is still relevant for sound cards in 2018, right?~~ _update: @rncbc thinks [this might still be the case](https://github.com/rncbc/qjackctl/issues/29#issuecomment-431654150)._ 

Second, if the framerate is indeed forced into a certain number, I think jack could improve messaging by saying something along the lines of:  
> Sample rate set at _n_, but device _hw:x,y_ forces playback at sample rate _i_.
  
This way, we can easily see the offending element in the chain.

Fourth, anyone know of other reasons that could cause this, or other solutions?

---

Using `jack`, `jack-tools` and `qjackctl` on Ubuntu 16.04 LTS.

```
$ jackd --version
jackdmp 1.9.11
```

```
00:00.0 Host bridge: Intel Corporation Device 5904 (rev 02)
00:08.0 System peripheral: Intel Corporation Sky Lake Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation Sunrise Point-LP USB 3.0 xHCI Controller (rev 21)
00:16.0 Communication controller: Intel Corporation Sunrise Point-LP CSME HECI (rev 21)
00:1f.3 Audio device: Intel Corporation Device 9d71 (rev 21)
```

**Comment by Redsandro** [comment]
Could someone with better knowledge about the JACK internals help me out?

Perhaps @jmendeth has a hunch?

I'm now on Ubuntu 18.04 (clean install) and I'm experiencing the same error.

**Empirical summary:** Connecting a 44 kHz input plays back one-ish tone higher at 48 kHz, leaving many little gaps (because there is not enough audio data in a 44 kHz second to fill a 48 kHz second).

Also tried [AskUbuntu](https://askubuntu.com/questions/1017620/how-to-change-playback-rate-for-use-with-jack).

**Comment by novadeviator** [comment]
@Redsandro have you ever found any solution to this? I'm looking at an internal soundcard on my new ThinkPad X1 that seems to not have a capability to play anything other than 48000. All my projects that use Jack (in ardour for example) use 44100. But it seems that ALSA is not converting the sample rate for jack. Found some posts online that say that JACK does not do any conversion and that soundcard needs to be able to play that sample rate. I'm looking into alsa configuration in order to force sample conversion, and how to fix that, but it's a learning curve.

**Comment by Redsandro** [comment]
@novadeviator I'm afraid I have not. I have spent an uncanny amount of time on trying to get this to work. Since 2016. Asked on different fora. Eventually opened a ticket. I'm frustrated that no one, _no one_ seems to know how exactly jack works. I especially love the suggestion from jack users that the problem I am describing is not possible.

All I wanted to do was play some guitar over my laptop. I am saddened but I have given up and crawled into a corner where it's dark with rain, forever.

**Comment by novadeviator** [comment]
@Redsandro The thing here seems that the integrated soundcard (I presume your 'output' soundcard is the intergrated one - mine is the intel hda one) are not really made for professional lowlatency audio work. 

I tried getting hardware info about my integrated soundcard with ```alsa-info``` command, ([see here](http://www.alsa-project.org/db/?f=19218cb76746b39c4b137bc76931524b9a3caac0)) and the analogue output seem to be capable only of 48000. so it might actually be down to hardware.

```
Node 0x02 [Audio Output] wcaps 0x41d: Stereo Amp-Out
  Control: name="Speaker Playback Volume", index=0, device=0
    ControlAmp: chs=3, dir=Out, idx=0, ofs=0
  Amp-Out caps: ofs=0x57, nsteps=0x57, stepsize=0x02, mute=0
  Amp-Out vals:  [0x48 0x48]
  Converter: stream=1, channel=0
  PCM:
    rates [0x40]: 48000
    bits [0xe]: 16 20 24
    formats [0x1]: PCM
````
(I'm using the latest Ubuntu Cosmic 18.10 with lowlatency kernel)

And it makes sense - since most applications (media players, browsers, pulseaudio) do the sampling conversion, in pro-audio you don't want to do too much of sampling conversion because it destroys your audio. In that sense it makes sense for JACK to not try to do any conversion at all but try to simply use whatever audio interface is capable of. I have accepted the fact that integrated audio forces JACK into 48000 and will not work with Ardour projects recorded in 44100. I can still use other programs like SuperCollider and Renoise, I can also just move my workflow into 48000, well, why not, if I want the convenience to edit audio with just a laptop and headphones on the road.

These days USB audio interfaces are really really cheap, so one solution for you would be to just get an additional USB soundcard for profesional audio work - like Behringer U-Phoria UMC22 is 35€ on thomann - you can combine it with your Vox device to have to USB interfaces, or you can simply record analogue output with the additional USB soundcard and not bother too much.

**Comment by Redsandro** [comment]
@novadeviator said:

> Do I understand correctly that ToneLabST has also an output? Why don't you use that as an output in your JACK? Just tell it to use only ToneLabsST as an input and output device and discard trying to get output from integrated Intel HDA card.

Never thought of that! This is good. If it works with both sounds mixed. I can attach the monitor speakers to the ToneLabs out instead.

**Comment by novadeviator** [comment]
@Redsandro I have completely solved my problem with simple advice from a linux audio wizard Robin Gareus. Solution was provided on Ardour forum: https://discourse.ardour.org/t/connecting-to-alsa-plug-layer-44100hz-projects-with-48000hz-capable-soundcard/100129/2?u=novaviator

in essence, it's very simple:
1) start jackd with a dummy driver with target sample rate - that's the rate you want/need to work in. in commandline this is
$ jackd -d dummy -r 44100
but this can be done also in qjackctl (Q Jackd Control)

2) start alsa_in and alsa_out with sampling rates that your input or output soundcard are capable of - I think this is possible only in console/terminal window:

$ alsa_in -d hw:0 -r 48000
$ alsa_out -d hw:0 -r 48000

the example above is for intergrated soundcard only. but this way you can bring in any number of soundcards with different sampling rates as ports in JACK. you can find out the 'name' of your soundcard with the command: 

$ aplay -l

look for card number as in "card: 0" or "card: 2" - that's what you put after "hw:". you can further specify specific port/output, by looking for "device: " in the `aplay -l` output and use that to specify something like "hw:0,3" (card,device)

hope that helps and sorry for hijacking the thread/issue. I feel that this solves the issue of different sampling rates with JACK and it could be closed - @Redsandro, what do you think?

**Comment by Redsandro** [comment]
> @Redsandro I have completely solved my problem with simple advice from a linux audio wizard Robin Gareus.

@novadeviator omg this would work? I'm excited to try this out. I'm on the road now. I will test this out with the equipment next year when I get home.
 
> hope that helps and sorry for hijacking the thread/issue. 

No sorry! If this works, which it probably will because it does for you, I'll be very happy you hijacked the issue.

> I feel that this solves the issue of different sampling rates with JACK and it could be closed - @Redsandro, what do you think?

I think technically you're right, but I'm wondering if this is an interesting case. While `jack` is awesome and it's making so many use cases possible, I have to admit that `jack` and `qjackctl` combined are the pinnacle of confusion, and while that was exactly adhering to the Linux tradition ~15 years ago, Linux has come a long way since then. These days, Linux users too are getting used to things working without needing to be a rocket scientist. 

This issue is a nice example of something that ideally would be detected, suggested and/or set up by the software. In stead, I gave up and it looks like I encountered a good Samaritan to show me the way years later. I observed this problem on all post-2013 computers I tried this on. The only computer where `jack`/`qjackctl` work as expected where even I can set it up is a desktop from 2003 with a dedicated sound card in the attic. It might be worth looking into automating the tricks necessary for using jack on the statistical mode (most frequently occurring) of hardware, which seems to me is laptops (and desktops) with an on-board sound processor that only supports this one frequency. This is usually 48 KHz, USB input is often 44 KHz  for older and 96 KHz for newer hardware.

Sorry, I'm rambling. I'll leave this open until I had a chance to test this out.

**Comment by 7890** [comment]
I will close this issue for the following reasons:

-Problem originates from audio hardware that won't support the requested SR
-Workaround for Ardour sessions was described: a) use dummy jack with desired SR b) route to/from hardware with bridges like zita-a2j
-For single audio files, the player programs will care about resampling to the current jackd SR

For special cases: run dummy jack at arbitrary SR, use zita-n2j as a resampling bridge to another instance of jackd (which eventually runs with a hardware backend).

The question remains if/how jackd could better warn in such situations or if it should startup at all.
"ERROR: playback and capture sample rates do not match (48000 vs. 44100)"

**Comment by jamshark70** [comment]
> The question remains if/how jackd could better warn in such situations or if it should startup at all.

Over on the SuperCollider forum, we just had an issue that was harder to troubleshoot than it needed to be, because Jack log messages report only the *requested* sample rate without noting any failure.

If the user asked for 44.1 and got 48, the logs simply should not leave it at "configuring for 44100." To switch sample rate without any notification to that effect is, in my view, no different from silent failure.

Please, yes, do improve the logging here.
