### ISSUE TITLE
question: pthread_t in windows

### ISSUE THREAD

**Issue by sonoro1234** [jackaudio/jack2#345]
Hi,

I am trying that this code already working in linux can be compiled in windows
<code>if (jack_client_thread_id(self->client) == pthread_self())</code>

for this to work I need
<code>typedef pthread_t jack_native_thread_t;</code>

and the way I found to get this was

```
#ifdef _WIN32
#define _PTHREAD_H
#endif
#include <jack/jack.h>
```

the above define is checked in https://github.com/jackaudio/jack2/blob/master/common/jack/systemdeps.h#L91

As I could not find any indication about that, my question is:
Is this the correct way to do it?

Best
victor bombi

**Comment by kmatheussen** [comment]
Hi, I'm pretty sure that you have to do
```
if (jack_client_thread_id(self->client) == GetCurrentThread())
```
in windows. If you look into JackWinThread.cpp in jack2, you'll see that jack_native_thread_t is mapped directly to windows thread handles.

**Comment by kmatheussen** [comment]
Seems like there's compilation options in Jack2 to use pthreads instead of native windows threads. 

However, the jack2 packages for windows are not compiled with pthreads, as far as I know. At least I've used native window threads in windows for the jack support in Radium, and that has worked well since 2012 or so.

The correct thing would be to test which pthread implementation jack uses at compile time (or perhaps even at runtime!), and then use correct version of pthread_self() or GetCurrentThread(), but I don't know any way to do that. It's probably safe to assume jack for windows always will use native windows threads though.
