### ISSUE TITLE
Bus error in Docker when run in privileged mode

### ISSUE THREAD

**Issue by angadn** [jackaudio/jack2#381]
_Problem 1:_  **Unable to allow for memlock inside container**
Things I've tried (unsuccessfully):
* `ulimit -l unlimited` (as well as replacing unlimited with a large value)
* `docker run --privileged ...`, `docker run --cap-add=SYS_NICE --cap-add=IPC_LOCK --cap-add=SYS_RESOURCE ...`
* I have run `usermod -a -G audio root` (as I'm on a Debian Docker Container)

I just can't seem to get rid of the ominous `Cannot lock down 82274202 byte memory area (Cannot allocate memory)`

Moreover, here is something even more cryptic...
_Problem 2:_ **privileges cause Bus Error**
* `docker run --privileged ...`
* `docker run --cap-add=SYS_RESOURCE ...`
* `docker run --cap-add=IPC_LOCK ...`

All of these cause a `jackd` Bus Error like so:

```
jackdmp 1.9.11
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
no message buffer overruns
no message buffer overruns
no message buffer overruns
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Cannot lock down 82274202 byte memory area (Cannot allocate memory)
Bus error (core dumped)
```

It seems `--cap-add=SYS_NICE` is the only one that is benign/doesn't cause this issue. 

**What's working right now**
When I don't try to increase my `ulimit -l` and don't add the additional privileges, JACKD works but I get a whole lot of page-swaps/poor performance :(

Really confused at this point and would appreciate any help my way :)

Thanks!

**Comment by falkTX** [comment]
Have you considered that perhaps you should not be doing this?
Why are you hurting yourself like this?

In any case, you are running a quite old version of jackd.
Before you try anything else, you need to update it.

But really, reconsider maybe what you are doing...

**Comment by angadn** [comment]
@falkTX Apologies if this sounds naive, but what about JACKD-in-Docker makes it a challenging setup?

Will checking a newer release - this seemed to be the latest on `apt-get`, and when I'd tried making from source I'd run into some other issues earlier; that was a long time ago though, will try an upgrade

**Comment by falkTX** [comment]
jack needs direct hardware access, and a reliable source for timing.
context switches (from the use of external clients) is going to be quite expensive inside a container.
I see no gain at all from this approach.

PS: also, since I saw you are trying to do go bindings for jack... before you get any further, notice that this will really results in big issues down the line.
Unless you are able to control the golang garbage collector (I mean, disable it completely), running golang binaries with jack will be a disaster waiting to happen.
I recommend you to read the usual http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing and think if a container (docker or even something else) can have the guarantees needed for realtime audio.

**Comment by angadn** [comment]
@falkTX thank you so much for your time and the heads-up on the Garbage collection. The article seems super-helpful.

As regards hardware-access, I thought I'd get away with it as I only need the `dummy` backend - I'm essentially trying to JACK audio out of Asterisk (the telephony server). There's certain limitations audio-streams would solve beautifully instead of Asterisk's existing API, and I picked JACK as its battle-hardened

**Comment by angadn** [comment]
Glad I had this advice at the right time - saved me weeks of suffering. Ended up with an alternative solution that works like a charm!
