### ISSUE TITLE
Support for virtual alias audio ports: Duplication of application input to multiple clients

### ISSUE THREAD

**Issue by twischer-adit** [jackaudio/jack2#401]
I am missing a feature to combine multiple input ports of different clients to one input port.
The following explains an use case:
* Two Lv2 plugins are already loaded and connected
* Both plugins require the same input (e.g. of an media player application)
* Therefore usually whenever the media player application starts it has to connect the same output port to two input ports

But to make all the connections easier to maintain an alias audio port could be introduced to combine the input ports of both Lv2 plugins. Therefore the media player only has to connect to the alias and does not need to know how many Lv2 plugins are involved. An audio route could then look like the following:
```
media player -> alias:media -> client1:in
                      |
                      +------> client2:in
```
This alias should not introduce additional audio buffer or addition copy efforts. JACK should only execute the connect commands for all ports of the alias when any application connects to the alisa. Therefore the following connections will be done:
* media player -> client1:in
* media player -> client2:in

If there is already a solution for such a use case existing it would be great if someone could explain me this solution. If not please give a feedback for my proposal. If this feature has a chance to be integrated I would like to implement it.

**Comment by 7890** [comment]
Hi, while there are a lot of additional things JACK could do, my feeling is that such a "splitter" is probably best implemented as a plugin. Some people use for instance a metering plugin, let all clients connect to it and then route from there to the desired outputs, usually system:playback. Basically JACK offers everything to reflect the outlined usecase, with a simple client doing the work. I am not aware of what an alias port type would introduce housekeeping-wise, the idea has some merit. Also think: "meta clients". Basically grouping clients to one. Now combine with alias ports. It can make everything more complicated. Keeping the core as simple as possible has some benefits IMO.

**Comment by twischer-adit** [comment]
@7890 
> my feeling is that such a "splitter" is probably best implemented as a plugin

An additional plugin would introduce additional copying efforts. I would like to use JACK on an embedded system. Therefore I try to keep the overhead as small as possible.

My current idea is to use the existing `SetAlias()` implementation of the `JackPort`. It looks like that multiple ports can have the same alias. Therefore I only have to extend `JackEngine::PortConnect()` to connect all ports with the same name and not only the first port with the matching name.
For me it looks like a small change set.

What do you think?

**Comment by 7890** [comment]
Yes, the copying is a downside. Related, there is http://drobilla.net/software/ingen which allows to make one LV2 plugin out of a graph of LV2 plugins. However I don't know if it would handle the outlined case with less buffer copying.

A totally different solution path would be to shape the plugin especially to fit the embedded restrictions and usecase, eg. one plugin gets one connection and handles the distribution client-internally (without copy). This possibly isn't feasible for every scenario.

If you think it's relatively easy to prototype alias ports, it would enable to test for possible edge-cases we don't consider yet. I have a feeling it could make things more complex (connections, clients and ports are all involved for changed semantics) but not necessarily. Maybe it can mess up with the main algorithm to process client buffers for one cycle (?).

Whether or not alias ports would be incorporated to JACK is a decision for others to take. It would most certainly need patches for both JACK 1 & 2 since there is an ongoing effort to unify theirAPIs and alias ports must be considered as a new feature.

**Comment by twischer-adit** [comment]
Discussion continuous in https://github.com/jackaudio/jack2/pull/409
