### ISSUE TITLE
[question] How to build Jack2 in a POSIX mode?

### ISSUE THREAD

**Issue by yurivict** [jackaudio/jack2#432]
Could you please add this to README?

**Comment by 7890** [comment]
@yurivict Please be more verbose, is there an issue?

**Comment by yurivict** [comment]
Somebody mentioned before that Jack2 is supposed to be buildable in a POSIX mode, without any OS-specific code.

**Comment by 7890** [comment]
Different POSIX versions are implemented to different degrees on different platforms, JACK uses POSIX or own mechanisms depending on platform. Even if platform compiles with POSIX header x, it can happen that calling the function will always fail (because not implemented).
@yurivict where did you pick up the "without any OS-specific code" ?

**Comment by 7890** [comment]
I think the answer is no, it's not possible to build JACK without any OS-specific code.
If this is not satisfying please rephrase the question and describe the issue in detail.
