### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [jackaudio/jack2#506]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by falkTX** [comment]
Yes, either today, tomorrow or very soon.
There is a PR to merge regarding meta-data (and filling out the rest of the description), plus 1 final metadata-related bug to fix.

**Comment by kloczek** [comment]
BTW .. do you have any plans to move to some more civilised build framework like automake/autoconf/libtool, meson or even cmake?

**Comment by falkTX** [comment]
not in the short or medium term, no.
calling autoconf more civilized must be a joke though... :laughing:

**Comment by kloczek** [comment]
Yes It is not as it can handle correctly LTO, fuzzing, coverage and many more without touch Makefile.am files.

**Comment by dvzrv** [comment]
I wouldn't be opposed to meson (as long as it's not cmake)! :-)
If I find some time in the coming weeks, I'd even consider doing a pull request for that.

**Comment by Jacalz** [comment]
I would really love seeing a meson build system. Meson is imo the most civilized build system and objectively the fastest of them all. It’s much faster than make with ninja but it is way better. Would be really cool to see that supported for building jack2 👍

**Comment by kloczek** [comment]
Just realised that build system is not the biggest jack2 problem.
It relies on few projects which development have been completely abandoned and those projects are only used by jack2.

**Comment by dvzrv** [comment]
@kloczek that's sadly not necessarily a new development in the free audio software/libraries domain. :D 
If you could identify them, please open a ticket for them (one at a time) and if you have suggestions as to how to improve the situation, it would of course be great to add it there. It is valuable information!

In regards to the build system (ouf, offtopic): waf (that is my personal opinion based on building a lot of software, that uses it) leads to extremely convoluted and complicated build system infrastructure, because people tend to use its "power" ("oh nice, I can do whatever python things in here"). IMHO, stuff should be easy to read, cross platform and to the point (with waf that is as far as I've seen never the case).

**Comment by kloczek** [comment]
waf is used only in handful of publicly used projects (probably not more than 20).

**Comment by kloczek** [comment]
Nevertheless please make new release as last tagged one cannot be used with python3.

**Comment by falkTX** [comment]
Final issue fixed. new release is tagged
https://github.com/jackaudio/jack2/releases/tag/v1.9.13
