### ISSUE TITLE
[Fetaure Request] JACK2 Portable

### ISSUE THREAD

**Issue by MrTeeXD** [jackaudio/jack2#539]
It would be great if JACK2 was portable for those who do not have their own PC and we can take it anywhere

**Comment by falkTX** [comment]
Not possible, JACK is a system-level library and service.
You could perhaps hack around things to make it work in a contained directory, not sure, but such thing would be completely unsupported.

**Comment by kmatheussen** [comment]
I agree though. Jack should be self-contained. There is no technical reason
why it couldn't be, and it would for sure make it easier for users not
having to deal with installing jack globally and sometimes having to mess
with incompatible versions of jack. Radium for Windows includes a special
version of Jack that is self-contained, and it's not "perhaps hack
around things" to make it work either, it's relatively simple.

**Comment by falkTX** [comment]
And I disagree.

JACK applications use libjack, which needs to know where to find JACK in the shared memory.
It is not just about finding libjack, that part is "easy", but also setting up the shared memory the same way between server and client.
This is a global operation, no way around it. We would have to tweak applications individually (like you do with Radium) or tweak each libjack to find different versions of JACK.
Plus also needs handling of multiple JACKs trying to run at the same time, or a conflict resolver of sorts.

Anyway, this is not the design goal of JACK. What you are doing *is* a hack, and not officially supported. Please stop recommending it.

**Comment by kmatheussen** [comment]
I know it's not as simple as what I have done in Radium, but it's still not
very hard. You just have to set up a global port/file/shared memory/etc.
pointing to where the currently used jack libraries are placed (jack
already does set up a globally accessible communication point), and then
recompile all programs using jack. I'm not suggesting that multiple Jack
servers should be running at the same time.

> Anyway, this is not the design goal of JACK. What you are doing is a
hack, and not officially supported. Please stop recommending it.

Just to be clear, I'm not attacking you personally in any way. This is just
how I think jack should work. The situation now is that it's quite messy
for the users. Users have to install jack, start a jack server, and
(usually) start a program to start the jack server as well.

**Comment by falkTX** [comment]
I understand your points, but I heavily disagree it is how JACK should behave.
We would be making JACK behave differently on Windows compared to all other platforms.

In your proposal, things are more complex the way I see it.
There will be different versions of JACK in the system. and the one that gets active depends on the application you start first.
The issue of having to start an application in order to start the JACK server is still there, independent of it being qjacktl or anything else.
The concept of updating your installed JACK version gets quite confusing here, since JACK becomes bundled with an application. JACK is delivered to the user via 3rd parties, arbitrary applications, instead of a central place. If the application stops being developed, there won't be more JACK updates then?

I know the current JACK situation on Windows is quite terrible, I have been ignoring it for quite some time. It is hard to care about these OSes that do not care about user freedom, and actively hurt the user instead.
But, at least on my side, things will change still this year. We will have a proper build for Windows later in the year, then I think we can see how to improve the situation.

**Comment by MrTeeXD** [comment]
I understand and I do apologise for bringing this up.
