### ISSUE TITLE
No Jack Router on MacOS?

### ISSUE THREAD

**Issue by jsl303** [jackaudio/jack2#618]
I'm running MacOS 10.14.6.
After I run jackd -d coreaudio, I can find JackRouter in some apps, but not all apps.
I can't find it in system preference > sound either.
Is there a way to make JackRouter to appear as normal sound device all apps?
Does the app have to support JackRouter specifically?

**Comment by falkTX** [comment]
JackRouter does not work since macOS 10.12

**Comment by jsl303** [comment]
Interesting... It seems to work in Logic though...

**Comment by zardini123** [comment]
What do you mean JackRouter doesn't work since macOS 10.12?  I'm running JackOSX which has JackRouter 0.9.7 and it works perfectly (for apps with Jack support).  Are you saying the functionality of it looking like an audio device has not been there since 10.12?

**Comment by jsl303** [comment]
I'm not sure about 10.12, but Jack Router doesn't even show up in Logic 
running on Catalina 10.15. It does appear in Logic running on Mojave 10.14.

**Comment by dyfer** [comment]
Just to clarify @falkTX 
JackRouter _does_ run on macOS **up to 10.14**, but with limitations: it can't be used as a default audio device and some applications can't use it. But it still works for many/most apps, as long as they are started after starting Jack server.
 
JackRouter uses an obsolete API. This API has been completely removed in macOS 10.15 (Catalina) and thus JackRouter does not run on Catalina.

**Comment by falkTX** [comment]
1.9.15 is out now, which no longer provides jack-router.

@sletz has written about his investigation regarding possibly making it work again at https://github.com/jackaudio/jack-router/blob/main/macOS/docs/JackRouter-AudioServerPlugin.md
maintainers welcome.

as for this ticket, I am closing it, since jack router is now no longer part of core jack2, and currently unsupported anyway.
