### ISSUE TITLE
modulo 8 output channel hopping

### ISSUE THREAD

**Issue by suedwestlicht** [jackaudio/jack2#620]
The MOTU Ultralite AVB USB audio interface either needs older firmware or a recent kernel with implicit feedback support and the attached patch. The patch is the preferred way since new versions of the MOTU Ultralite AVB (with ESS chips) cannot load the older firmware.

Both modes of operandi have a modulo 8 channeloutput hopping problem.

With the newer kernel and firmware it can be triggered by changing jackd's buffer size on the fly with jack_bufsize. Then what's system:playback_1 ends on channel 1, 9 or 17 on the MOTU. It has 24 ins and outs.

Since restarting jackd fixes it for some time (until a buffer size change or sometimes for an unknown reason) it could be that there's an error in jackd.

Where can I start to debug to find out what happens?

[drumbell_avb-patch_for_linux_5.8.rc6.txt](https://github.com/jackaudio/jack2/files/4983701/drumbell_avb-patch_for_linux_5.8.rc6.txt)

**Comment by dvzrv** [comment]
@suedwestlicht I doubt that this issue is at all related to jack though. I've used this device before and it's a major pain on Linux, unless a specific firmware is installed (and even than it is glitchy at best). In fact, many people have had issues with the hardware (see [relevant linuxmusicians forum thread](https://linuxmusicians.com/viewtopic.php?f=6&t=18046)).

All in all you can always start jackd with verbose flags (see `man 1 jackd`).

Unrelated: Has the above patch been upstreamed to ALSA?

**Comment by suedwestlicht** [comment]
Someone on Linuxmusicians reported that it happens with ALSA clients, too. So I guess we can close the issue and I should report it to ALSA.
