### ISSUE TITLE
Release scheme for tarball releases?

### ISSUE THREAD

**Issue by rubyFeedback** [jackaudio/jack2#621]
Hello jack2 devs,

This is a tiny issue, not sure if I should report it - but since it is smallish, perhaps
it is simple to change.

The older release allowed this scheme:

https://github.com/jackaudio/jack2/releases/download/v1.9.13/jack2-1.9.13.tar.gz

The new URL is:

https://github.com/jackaudio/jack2/releases/download/v1.9.14/v1.9.14.tar.gz

This is a bit harder to parse in shell scripts since the leading "jack2" is missing.

Again, it's not a big deal, but if it would be possible, could the old URL scheme
be retained, which also had the name of the program? It would help a bit in
downstream scripts that automate installing and compiling programs like
jack2 from source. At any rate, feel free to close this issue at any moment
in time - thank you for reading this issue request.

**Comment by falkTX** [comment]
This could be better like that yes. the last source tarball is something created by github not manually, that is why it is missing the name prefix.
I am working on automated builds for jack2, originally meant for windows and macos binaries, but it makes sense to generate a source tarball too (specially since we will use git submodules soon, and github does not handle those well).

I went ahead and uploaded a tarball with the correct naming. Thanks for bringing up the issue
so the link https://github.com/jackaudio/jack2/releases/download/v1.9.14/jack2-1.9.14.tar.gz works now
