### ISSUE TITLE
For the Windows installer lib files should exists in C:/Program Files/JACK2/lib

### ISSUE THREAD

**Issue by ReinholdH** [jackaudio/jack2#637]
On Windows the JACK installers place the libjack.dll and libjack64.dll into C:\Windows. With the files in C:\Windows they are available for Windows apps. Windows apps even commercial Windows apps can use them under the LGPL license. This requires that the include files are available in include/jack (they are) and the lib files need to be available as well.

It would be very helpful having these lib files included into the lib directory. The lib files are pretty small and do not count to the size of the installation file. Having the libs available in the installers will help Windows apps a lot and avoid creating these libs through MinGW and/or through a combination of Windows tools. Further, it is assured that the include files, dlls and libs always fit together for everybody.

Using Jack on Windows would then just require:
- For the Windows app development: install jack, use the include path for compiling, use the lib file for linking
- For Windows end users: install jack, install the Windows app which uses jack

**Comment by falkTX** [comment]
Indeed.

The missing lib files is just out of my inexperience with using MSVC.
For mingw, I already have confirmation (from zrythm developer) that the new jack2 installer files work correctly, both for developer usage and also end-users.

**Comment by falkTX** [comment]
Got something that might work. Build at https://github.com/jackaudio/jack2-releases/releases/tag/untagged-a8f582812ebe61f5195a
Let me know if/how it works, thanks!

**Comment by ReinholdH** [comment]
At a first glance is looks great. But let me check over the weekend to provide a final answer. Big Thx.

**Comment by ReinholdH** [comment]
I tested the new Windows builds for Win32 and x64 and they looks good. Thanks a lot.
In order to properly build the Steinberg VST3 SDK the paths were adapted in the cmake file to

JACK2 Win32

    PROGRAM_FILE_JACK_INCLUDE "C:/Program Files (x86)/JACK2/include"
    PROGRAM_FILE_JACK_LIB "C:/Program Files (x86)/JACK2/lib"

JACK2 x64

    PROGRAM_FILE_JACK_INCLUDE "C:/Program Files/JACK2/include"
    PROGRAM_FILE_JACK_LIB "C:/Program Files/JACK2/lib"


The default path in Steinberg's SDK is

Steinberg SDK 3.7.0  (vst-sdk_3.7.0_build-116_2020-07-31)

    PROGRAM_FILE_JACK_INCLUDE "C:/Program Files (x86)/Jack/includes"
    PROGRAM_FILE_JACK_LIB "C:/Program Files (x86)/Jack/lib"

At a first attempt the "..\include" vs. "..\includes" was confusing. Could be - not sure - whether Jack 1 has beein using "includes". A consistant use would be helpful.

**Comment by falkTX** [comment]
> At a first attempt the "..\include" vs. "..\includes" was confusing. Could be - not sure - whether Jack 1 has beein using "includes". A consistant use would be helpful.

Old installer was also for JACK2, but managed manually by a different person.
I named the folder "include" because it is the more common word for it.
I do not have intentions of changing this going forward, everyone/everything pretty much uses the "include" term, not "includes".

The change of "Jack" to "JACK2" is something just because it makes more sense.
JACK2 is not JACK itself, but an implementation of it. JACK1 and PipeWire provide alternative implementations, and there is one inside Carla too.

The installer path had to change anyway, since the old installer always used 32bit path.
The new one correctly puts it in the regular, 64bit related program files.

Anyway, I am tempted to close this ticket since the issue around it is fixed.
Unless you have any more feedback...?

**Comment by ReinholdH** [comment]
Thanks for the immediate response. I like "include" much more than "includes" because it is used everywhere and common practice, just want you to know.

Yes, you can close the ticket as Done.

Thank you very much for taking immediate action on the issue #637.

I am looking forward to an official Windows version.

**Comment by falkTX** [comment]
Thanks for the feedback!

> I am looking forward to an official Windows version.

Current plan is for October 15

**Comment by falkTX** [comment]
Forgot to close this ticket before, going to do that now.

@ReinholdH I checked your last report, very useful thanks.
Would you be so kind as to report the issues here on this bug tracker?
The 1st one is already fixed, but because you installed the new JACK2 builds before it does not get the proper value (so you open regedit under HKCU/Software/rncbc.org and delete the QjackCtl stuff. On the next startup it will have the proper (default) values.
```
17:55:17.261 Statistics reset.
17:55:35.852 JACK is starting...
17:55:35.853 C:/Program Files/JACK2/jackd.exe -S -X winmme -dportaudio -r48000 -p1024
17:55:35.874 JACK was started with PID=32998704.
jackdmp 1.9.14
...
```
And the last issue I already reported against QjackCtl here https://github.com/rncbc/qjackctl/issues/104. Going to do a tentative fix of this soon.

Thanks again!

**Comment by falkTX** [comment]
hmm it might need a delete of the previous `.jackdrc` file too
