### ISSUE TITLE
Windows 10, Ableton doesn't see Jack

### ISSUE THREAD

**Issue by BenDS1984** [jackaudio/jack2#684]
Hi,
With Jack1 audio I needed to register the jackrouter.dll file to make ableton see jack audio.
But I recently had to reinstall everything and Jack audio is now on version 2, and there is no jackrouter.dll file anymore to register, and Ableton does not see jack...
In Bitwig everything is fine, there I can select jack...
Anyone with a solution?
Thx!

**Comment by szszoke** [comment]
Ableton has no native support for Jack.

You would need Jack Router which would create a virtual ASIO device which would also appear in your Jack graph.

Jack Router was removed from the latest Windows release because it is not maintained. You should still be able to download it from here: https://github.com/jackaudio/jack-router/tree/main/binaries/win64

**Comment by falkTX** [comment]
jack-router is coming back in the next release in 7 days.
pre-release binaries at https://github.com/jackaudio/jack2-releases/releases/tag/untagged-dc253c3f5ca380ada300 already include jack-router

**Comment by szszoke** [comment]
Did someone stepped up for maintaining `JackRouter`?

**Comment by falkTX** [comment]
not quite, but the builds were updated to latest Visual Studio.
As-is the resulting binaries work.

So as long as it is opt-in, disabled by default, I am okay with having those in the windows installer.
Better this way that makes installation a lot easier, so we will end up with less reported issues from users not exactly knowing how to activate the driver.
