### ISSUE TITLE
QJackCtl "look and feel" on macOS

### ISSUE THREAD

**Issue by dyfer** [jackaudio/jack2#713]
## Describe the bug

On macOS 10.14, the latest QJackCtl from Jack2 1.9.17 doesn't seem to use cocoa's/system's "look and feel". QJackCtl from the previous installer (1.9.16) _did_ have system's look.

## Environment

* **JACK Version:** 1.9.17
* **Operating System:** macOS 10.14
* **Installation:** From the [installer](https://github.com/jackaudio/jack2-releases/releases/tag/v1.9.17) 

## Steps To Reproduce

- Download the installer
- Open QJackCtl

### Expected vs. actual behavior

Expected:
![Screen Shot 2021-01-25 at 16 02 24](https://user-images.githubusercontent.com/1589177/105781134-d57bfa00-5f26-11eb-811e-28c134578128.png)
Actual:
![Screen Shot 2021-01-25 at 16 03 03](https://user-images.githubusercontent.com/1589177/105781145-dad94480-5f26-11eb-8324-0d0ee2d2efcb.png)

**Comment by falkTX** [comment]
This is intentional, some of the custom widgets in qjackctl do not look proper in macOS.
I changed the defaults so that it uses Fusion theme and KXStudio color scheme, but if you already had JACK2 installed before those are not automatically applied. It is easy to change from the settings in either case.

As qjackctl main target is not macOS but Linux, it is very unlikely fixing up the widgets for macOS use will ever get done.
So this was a sorta compromise.

**Comment by dyfer** [comment]
Thanks for a quick reply @falkTX, this makes sense.
I missed the widget setting, sorry about that.
Which widgets don't look properly on macOS?

**Comment by falkTX** [comment]
I do not recall now sorry, but it was more obvious when using the dark theme of macOS.
I do remember that at least tabs (as in separator widgets) did not look correctly.

**Comment by dyfer** [comment]
Thanks!
