### ISSUE TITLE
JackClient::AcquireSelfRealTime fails on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [jackaudio/jack2#865]
Arfour6 fails to create a session with this error:
```
Could not create session in "/home/yuri/Untitled-2022-04-17-09-54-44"

---ERROR: JACK: Cannot create thread res = 1
ERROR: JACK: JackClient::AcquireSelfRealTime error
ERROR: JACK: Cannot use real-time scheduling (RR/5) (1: Operation not permitted)
```

This appears to be due to the lack of real-time support in Jack.

FreeBSD [bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=263373).

jackit-1.9.20_1
FreeBSD 13

**Comment by 0EVSG** [comment]
Hi Yuri,
realtime support should be fine with both JACK and Ardour - looks like your user doesn't have realtime privileges, usually only root has that on FreeBSD. You can either:

 * Disable realtime in the configuration / CLI arguments.
 * Wait for FreeBSD 13.1 to be released, load the `mac_priority` module and add your user to the `realtime` group.

Hope that helps!

**Comment by yurivict** [comment]
idprio(1) shows that the daemon runs at realtime priority 0.
Same problem occurs when the Ardour process is set 0 priority.

**Comment by falkTX** [comment]
at least on linux rt prio 0 means no actual rt priority is set, the SCHED_OTHER type of scheduling which is for all "normal" non-rt programs

**Comment by yurivict** [comment]
On FreeBSD prio=0 is a real-time priority.

**Comment by 0EVSG** [comment]
@falkTX: Priority numbers are quite different from Linux, only the POSIX scheduling hints (SCHED_OTHER et al) are the same.

@yurivict: I suppose you used `rtprio(1)` to give Ardour real-time privilege, right?

If I remember correctly, Ardour expects to start with normal user priority, and only elevates some threads to real-time priority when needed, otherwise switching back to user priority. That makes sense, because you don't want some non-critical GUI thread to block the timing-sensitive audio threads.

In your case, the whole Ardour process starts with real-time priority, but explicitly drops the real-time privilege on the relevant thread, since it's not needed at that point in time. Later it tries to re-elevate the thread to real-time priority, which fails - FreeBSD only allows this if the user has permission, even though the other Ardour threads still run with real-time priority.

That was actually one of the main motivations for the `mac_priority` module in the upcoming FreeBSD 13.1 release.

**Comment by 0EVSG** [comment]
Closing this, as I don't think any action on Jack side is needed.
